# Generated by Django 4.2.9 on 2024-09-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile", name="bio", field=models.TextField(blank=True),
        ),
    ]
