# Generated by Django 4.2.9 on 2024-09-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_dislike"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(to="blog.category"),
        ),
    ]
